### ISSUE TITLE
Document in `HACKING.md` how to install pre-commit hooks for developers

### ISSUE THREAD

**Issue by MatthewDaggitt** [vehicle-lang/vehicle#230]

**Comment by MatthewDaggitt** [comment]
Also apparently `pre-commit` only seems to work for Python 3.7 and above. I get the following error message on Python 3.6.8 on windows:
```
git commit -m "Add"
[INFO] Initializing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('C:\\Users\\mdagg\\.cache\\pre-commit\\repoth9c2rfc\\py_env-python3.6\\Scripts\\python.EXE', '-mpip', 'install', '.')
return code: 1
expected return code: 0
stdout:
    Processing c:\users\mdagg\.cache\pre-commit\repoth9c2rfc
      Preparing metadata (setup.py): started
      Preparing metadata (setup.py): finished with status 'error'

stderr:
      ERROR: Command errored out with exit status 1:
       command: 'C:\Users\mdagg\.cache\pre-commit\repoth9c2rfc\py_env-python3.6\Scripts\python.EXE' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\mdagg\\.cache\\pre-commit\\repoth9c2rfc\\setup.py'"'"'; __file__='"'"'C:\\Users\\mdagg\\.cache\\pre-commit\\repoth9c2rfc\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\mdagg\AppData\Local\Temp\pip-pip-egg-info-3xycdegm'
           cwd: C:\Users\mdagg\.cache\pre-commit\repoth9c2rfc\
      Complete output (6 lines):
      Traceback (most recent call last):
        File "<string>", line 1, in <module>
        File "C:\Users\mdagg\.cache\pre-commit\repoth9c2rfc\setup.py", line 1
          from __future__ import annotations
          ^
      SyntaxError: future feature annotations is not defined
      ----------------------------------------
    WARNING: Discarding file:///C:/Users/mdagg/.cache/pre-commit/repoth9c2rfc. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
    ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

Check the log at C:\Users\mdagg\.cache\pre-commit\pre-commit.log
```

**Comment by wenkokke** [comment]
Unfortunately, pre-commit will use any `python3` installed.

**Comment by wenkokke** [comment]
However, you should probably upgrade that Python version?

I believe `vehicle-python` already requires Python 3.10, but I suppose documenting the additional constraint for the pre-commit hooks won’t harm.
