### ISSUE TITLE
Error running tox tests locally

### ISSUE THREAD

**Issue by MatthewDaggitt** [vehicle-lang/vehicle#564]
```bash
tox
py37 create: /home/matthew/Code/AISEC/vehicle/py-vehicle-lang/.tox/py37
py37 inst: /home/matthew/Code/AISEC/vehicle/py-vehicle-lang/.tox/.tmp/package/1/vehicle_lang-0.3.3.tar.gz
py37 installed: astunparse==1.6.3,exceptiongroup==1.1.1,importlib-metadata==6.6.0,iniconfig==2.0.0,packaging==23.1,pluggy==1.0.0,pytest==7.3.1,six==1.16.0,tomli==2.0.1,typing_extensions==4.6.3,vehicle-lang @ file:///home/matthew/Code/AISEC/vehicle/py-vehicle-lang/.tox/.tmp/package/1/vehicle_lang-0.3.3.tar.gz,zipp==3.15.0
py37 run-test-pre: PYTHONHASHSEED='774364232'
py37 run-test: commands[0] | /home/matthew/Code/AISEC/vehicle/py-vehicle-lang/.tox/py37/bin/python -m pytest
===================================== test session starts ======================================
platform linux -- Python 3.7.16, pytest-7.3.1, pluggy-1.0.0
cachedir: .tox/py37/.pytest_cache
rootdir: /home/matthew/Code/AISEC/vehicle/py-vehicle-lang
configfile: pyproject.toml
testpaths: tests
collected 20 items / 1 error                                                                   

============================================ ERRORS ============================================
______________________ ERROR collecting tests/test_loss_function_exec.py _______________________
ImportError while importing test module '/home/matthew/Code/AISEC/vehicle/py-vehicle-lang/tests/test_loss_function_exec.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../../../.pyenv/versions/3.7.16/lib/python3.7/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_loss_function_exec.py:6: in <module>
    from vehicle_lang import session
.tox/py37/lib/python3.7/site-packages/vehicle_lang/session.py:12: in <module>
    from ._binding import _unsafe_vehicle_free, _unsafe_vehicle_init, _unsafe_vehicle_main
E   ImportError: libHSvehicle-0.3.3-inplace-ghc9.4.4.so: cannot open shared object file: No such file or directory
=================================== short test summary info ====================================
ERROR tests/test_loss_function_exec.py
!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!
======================================= 1 error in 0.30s =======================================
ERROR: InvocationError for command /home/matthew/Code/AISEC/vehicle/py-vehicle-lang/.tox/py37/bin/python -m pytest (exited with code 2)
```

**Comment by wenkokke** [comment]
@MatthewDaggitt Please confirm that this is fixed!

**Comment by MatthewDaggitt** [comment]
Unfortunately not. I now get the error: 
```
Traceback (most recent call last):
  File "/usr/bin/tox", line 33, in <module>
    sys.exit(load_entry_point('tox==3.21.4', 'console_scripts', 'tox')())
  File "/usr/lib/python3/dist-packages/tox/session/__init__.py", line 44, in cmdline
    main(args)
  File "/usr/lib/python3/dist-packages/tox/session/__init__.py", line 65, in main
    config = load_config(args)
  File "/usr/lib/python3/dist-packages/tox/session/__init__.py", line 81, in load_config
    config = parseconfig(args)
  File "/usr/lib/python3/dist-packages/tox/config/__init__.py", line 280, in parseconfig
    ParseIni(config, config_file, content)
  File "/usr/lib/python3/dist-packages/tox/config/__init__.py", line 1228, in __init__
    self.handle_provision(config, reader)
  File "/usr/lib/python3/dist-packages/tox/config/__init__.py", line 1308, in handle_provision
    env_config = self.make_envconfig(
  File "/usr/lib/python3/dist-packages/tox/config/__init__.py", line 1407, in make_envconfig
    res = meth(env_attr.name, env_attr.default, replace=replace)
  File "/usr/lib/python3/dist-packages/tox/config/__init__.py", line 1703, in getargvlist
    return _ArgvlistReader.getargvlist(self, s, replace=replace, name=name)
  File "/usr/lib/python3/dist-packages/tox/config/__init__.py", line 1967, in getargvlist
    commands.append(cls.processcommand(reader, current_command, replace, name=name))
  File "/usr/lib/python3/dist-packages/tox/config/__init__.py", line 1993, in processcommand
    new_word = reader._replace(word, name=name)
  File "/usr/lib/python3/dist-packages/tox/config/__init__.py", line 1788, in _replace
    replaced = Replacer(self, crossonly=crossonly).do_replace(value)
  File "/usr/lib/python3/dist-packages/tox/config/__init__.py", line 1824, in do_replace
    expanded = substitute_once(value)
  File "/usr/lib/python3/dist-packages/tox/config/__init__.py", line 1822, in substitute_once
    return self.RE_ITEM_REF.sub(self._replace_match, x)
  File "/usr/lib/python3/dist-packages/tox/config/__init__.py", line 1895, in _replace_match
    return self._replace_substitution(sub_value)
  File "/usr/lib/python3/dist-packages/tox/config/__init__.py", line 1930, in _replace_substitution
    val = self._substitute_from_other_section(sub_key)
  File "/usr/lib/python3/dist-packages/tox/config/__init__.py", line 1925, in _substitute_from_other_section
    raise tox.exception.ConfigError("substitution key {!r} not found".format(key))
tox.exception.ConfigError: ConfigError: substitution key 'env_python' not found
```

I've looked around and the error seems to be being thrown here:

https://github.com/vehicle-lang/vehicle/blob/d33169a6963f594304d3964fe5ca5a909f6d2d1b/py-vehicle-lang/pyproject.toml#L93

Looking at the changes you made over the weekend you seem to have changed `pythonenv` to `python_env` but if I change it back I get the same error but with `package_root` on the next line.

**Comment by wenkokke** [comment]
What version of tox are you using?

**Comment by MatthewDaggitt** [comment]
3.21.4

**Comment by wenkokke** [comment]
That's a very old version. Please see if you can update it, or otherwise run tox via pipx as `pipx run tox`.

We require at least version 4.

**Comment by MatthewDaggitt** [comment]
Thanks, running now. Will close if it goes through.

**Comment by MatthewDaggitt** [comment]
Getting there. Built the wheel successfully, but now missing something called `patchelf`? I guess I should be installing that manually?
```
Successfully built vehicle_lang-0.3.3-cp311-cp311-linux_x86_64.whl
INFO:auditwheel.main_repair:Repairing vehicle_lang-0.3.3-cp311-cp311-linux_x86_64.whl
Traceback (most recent call last):
  File "/home/matthew/Code/AISEC/vehicle/py-vehicle-lang/.tox/build-py311/bin/auditwheel", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/matthew/Code/AISEC/vehicle/py-vehicle-lang/.tox/build-py311/lib/python3.11/site-packages/auditwheel/main.py", line 59, in main
    rval = args.func(args, p)
           ^^^^^^^^^^^^^^^^^^
  File "/home/matthew/Code/AISEC/vehicle/py-vehicle-lang/.tox/build-py311/lib/python3.11/site-packages/auditwheel/main_repair.py", line 174, in execute
    patcher = Patchelf()
              ^^^^^^^^^^
  File "/home/matthew/Code/AISEC/vehicle/py-vehicle-lang/.tox/build-py311/lib/python3.11/site-packages/auditwheel/patcher.py", line 45, in __init__
    _verify_patchelf()
  File "/home/matthew/Code/AISEC/vehicle/py-vehicle-lang/.tox/build-py311/lib/python3.11/site-packages/auditwheel/patcher.py", line 29, in _verify_patchelf
    raise ValueError("Cannot find required utility `patchelf` in PATH")
ValueError: Cannot find required utility `patchelf` in PATH
The built wheel is located in /home/matthew/Code/AISEC/vehicle/py-vehicle-lang/dist
py311: failed with no package found in /home/matthew/Code/AISEC/vehicle/py-vehicle-lang/dist/*cp311*.whl
  py37: FAIL code 1 (113.55 seconds)
  py38: FAIL code 1 (128.70 seconds)
  py39: FAIL code 1 (120.25 seconds)
  py310: FAIL code 1 (0.39 seconds)
  py311: FAIL code 1 (122.47 seconds)
  evaluation failed :( (485.40 seconds)
```

**Comment by MatthewDaggitt** [comment]
Okay installed `patchelf` via `apt install patchelf` and trying again.

**Comment by MatthewDaggitt** [comment]
Okay all versions built except for py310 which failed with:
```
build-py310: commands[0]> sh /home/matthew/Code/AISEC/vehicle/py-vehicle-lang/scripts/build-wheel.sh
* Creating venv isolated environment...
The virtual environment was not created successfully because ensurepip is not
available.  On Debian/Ubuntu systems, you need to install the python3-venv
package using the following command.

    apt install python3.10-venv

You may need to use sudo with that command.  After installing the python3-venv
package, recreate your virtual environment.

Failing command: ['/tmp/build-env-p3p_tm7i/bin/python', '-Im', 'ensurepip', '--upgrade', '--default-pip']

usage: auditwheel [-h] [-V] [-v] command ...
auditwheel: error: cannot access /home/matthew/Code/AISEC/vehicle/py-vehicle-lang/.tox/build-py310/tmp/dist/*.whl. No such file
The built wheel is located in /home/matthew/Code/AISEC/vehicle/py-vehicle-lang/dist
py310: failed with no package found in /home/matthew/Code/AISEC/vehicle/py-vehicle-lang/dist/*cp310*.whl
py310: FAIL ✖ in 0.27 seconds
```

I'm a bit puzzled by this. I'm not quite sure what's different between 39, 310 and 311 that would cause only 310 to fail.

**Comment by wenkokke** [comment]
Did you follow the suggested instructions?

**Comment by MatthewDaggitt** [comment]
No, as I have to confess I'm not quite sure how it interacts with `pyenv`. Do I somehow need to install it with `pyenv` specifically for 310 or can I get away with installing it globally?

**Comment by wenkokke** [comment]
I'm assuming you have Python 3.10 installed via PyEnv?

**Comment by MatthewDaggitt** [comment]
Yes.

**Comment by wenkokke** [comment]
Maybe it's finding the Ubuntu Python 3.10 first, which presumably needs a Ubuntu managed venv?

**Comment by MatthewDaggitt** [comment]
Okay, I installed it globally and now everything passes :tada: I'm going to leave this open until I port some of it to the HACKING file.

Thanks for your help!
